# Generated by Django 4.2.2 on 2023-06-22 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='text')),
                ('correct', models.BooleanField(default=False, verbose_name='correct')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(max_length=200, verbose_name='text')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('number_of_questions', models.IntegerField(verbose_name='number of questions')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='quiz_submit_date')),
                ('score_to_pass', models.IntegerField(help_text='required score in %', verbose_name='required score to pass')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizes',
                'ordering': ['name', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='score')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='quiz_submit_date')),
                ('questions_attempted', models.ManyToManyField(related_name='result_attempts', to='quiz_app.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz_app.quiz', verbose_name='result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('user_answers', models.ManyToManyField(blank=True, related_name='user_results', to='quiz_app.answer', verbose_name='user answers')),
                ('user_incorrect_answers', models.ManyToManyField(blank=True, related_name='user_incorrect_results', to='quiz_app.answer', verbose_name='user incorrect answers')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ManyToManyField(help_text='choose topic(s) for this quiz', to='quiz_app.topic', verbose_name='topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz', verbose_name='quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question', verbose_name='question'),
        ),
    ]
