# Generated by Django 4.2.2 on 2023-06-20 21:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='text'),
        ),
    ]
